### ISSUE TITLE
Support dnd5e versatile field.

### ISSUE THREAD

**Issue by FurtherV** [krbz999/rollgroups#14]
Based on discord conversation https://discord.com/channels/170995199584108546/670336046164213761/1088860790834069605.

Currently when there are multiple roll groups and formulas, the last formula gets added to the versatile formula which is incorrect behavior. Instead the versatile formula should entirely replace all other formulas.

For example, assume we have a very cool weapon that is +1 and does 2d6 damage and versatile 2d8 damage with a saving throw for 4 fire damage. This is the setup:
1. Formula: `2d6 + @mod + 1 | Slashing`
2. Formula: `4 | Fire`
Versatile: `2d8 + @mod + 1`
Two Roll groups, A and B with A having the first formula and B having the second formula.

Rolling via the rollgroups buttons works fine but if you roll using the Versatile button instead of rolling `2d8 + @mod  + 1` it will roll `2d8 + @mod + 1 + 4`. The 4 seems the originate from the second formula. This is not intended behavior I think and is confusing for the user.

A solution would be to completely replace the versatile button with its own roll group or disable it or something.

**Comment by RossGosling** [comment]
I feel like a similar problem could be made with Other Formula?

I run my Longsword like this:
![image](https://user-images.githubusercontent.com/879127/227598372-056755a8-fecb-424f-9143-c961ae571a96.png)
![image](https://user-images.githubusercontent.com/879127/227598543-a1c9a80a-1888-4f9c-a184-5b56f9d214d7.png)

Feels like Versatile and Other Formula could be moved into respective roll groups as you suggest

**Comment by krbz999** [comment]
This is where Roll Groups diverges from its predecessor (Minimal Rolling Enhancements); it won't remove the need for the Versatile field or hide it. I think the simplest solution is to select which group the Versatile button rolls, and - as in core - replace the first formula in that group with its own formula.

That would cover both use cases presented here but would not cover the use case of very complicated roll group setups.

As for the Other Formula field, my opinion is that it isn't a damage roll (and core doesn't treat it as such). It's used for *related* rolls such as, "On a hit, roll a d6, if you roll 5 or higher, then [something happens]." Given its nature, I don't think it needs to be touched by this module.
