### ISSUE TITLE
Group Config cannot be rendered if the item is versatile but has no module flag

### ISSUE THREAD

**Issue by ghost** [krbz999/rollgroups#15]
When I click on the button, this is the error I get:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/79125274/227730803-7dc1e4d0-b8c9-4a7a-a87d-81aaecf54023.png">

**Comment by krbz999** [comment]
I was able to reproduce this only with an item that has a versatile formula but no regular damage formulas. What does the item in question look like?

**Comment by ghost** [comment]
A spear normal
