### ISSUE TITLE
Group Config Not Appearing

### ISSUE THREAD

**Issue by ZiaMeza** [krbz999/rollgroups#22]
Howdy, just starting off by saying I love this module. It's such a great addition for so many scenarios, especially once-per-turn or per-round effects.

I'm updated to the latest version of Roll Groups, Version 11.0.1, and I'm on the latest version of DnD5e (2.2.1). Ever since the latest update to Roll Groups, I've noticed that the group configuration button is not showing up. 

Other useful information is that this is Foundry Version 10, Build 291.

Much thanks for the consideration!

![image](https://github.com/krbz999/rollgroups/assets/11086640/f3d50e29-3f90-40b2-8ce4-1ca71521a45a)

**Comment by krbz999** [comment]
I am not able to reproduce this. Please provide screenshots of any errors and disable all other modules.

**Comment by ZiaMeza** [comment]
.

Please ignore me; I think in the process of troubleshooting the module, I had turned it off, and neglected to turn it back on.

It is working as expected now. Apologies.

**Comment by krbz999** [comment]
Happens all too often. Glad to hear there are no issues.
