### ISSUE TITLE
Create damage roll messages with multiple rolls in.

### ISSUE THREAD

**Issue by krbz999** [krbz999/rollgroups#3]
This would probably be pointless until the system allows applying damage per roll rather than per message.

**Comment by pal-rgosling** [comment]
To pull from Minimal Rolling Enhancements description, does this issue seek to replicate this functionality?
![image](https://user-images.githubusercontent.com/32677327/195992880-4f4d3c2f-ceab-4bcb-9658-be56e53db640.png)

**Comment by RossGosling** [comment]
To pull from Minimal Rolling Enhancements description, does this issue seek to replicate this functionality?
![image](https://user-images.githubusercontent.com/32677327/195992880-4f4d3c2f-ceab-4bcb-9658-be56e53db640.png)

**Comment by krbz999** [comment]
Yes.

**Comment by krbz999** [comment]
Ideally this would not need to be part of a module at all, but all damage rolls would split into multiple rolls by default in the system, using the `system.damage.parts` array -- each element of the array being one roll.

**Comment by krbz999** [comment]
This will be added to the system, albeit slowly, so is best left out of a module.
