### ISSUE TITLE
Damage and Cure

### ISSUE THREAD

**Issue by Kharmans** [krbz999/rollgroups#30]
When I configure a roll group that has a damage and a cure, it always roll damage, even if I choose the cure.

**Roll Goups**: v11.2.2
**DnD5e**: v2.4.1

**Comment by krbz999** [comment]
Can you provide steps to reproduce this?

**Comment by Kharmans** [comment]
Yes, and I forgot to mention that this happen when using MidiQOL to automatic applied the damage.

1- Create two damage types with one of then being a cure or temp hp;
2- Roll the attack;
3- Click on Heal button (of the Roll Groups) on chat card;
4- See the damage be applied instead of the heal.

**Comment by krbz999** [comment]
And how about without midi?

**Comment by Kharmans** [comment]
Without midi the damage or heal are not applied. The system don't applied the damage automatically.

**Comment by krbz999** [comment]
This module has never been compatible with midi, and it never will be. If midi causes an issue, then it's a midi issue.

Closing as wontfix as there is nothing to change here.
